import { MigrationInterface, QueryRunner } from "typeorm";

export class Initial1778342534203 implements MigrationInterface {
    name = 'Initial1778342534203'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "faqs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "question" character varying NOT NULL, "answer" text NOT NULL, "category" character varying, "order" integer NOT NULL DEFAULT '0', "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_2ddf4f2c910f8e8fa2663a67bf0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3816a9b513ab119616229d3356" ON "faqs" ("order") `);
        await queryRunner.query(`CREATE INDEX "IDX_821beb737b3c154e7cbc83aff4" ON "faqs" ("isActive") `);
        await queryRunner.query(`CREATE INDEX "IDX_97f324118f8227531259b3a558" ON "faqs" ("category") `);
        await queryRunner.query(`CREATE TYPE "public"."users_userrole_enum" AS ENUM('contractor', 'supplier', 'admin')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying, "phoneNumber" character varying, "password" character varying NOT NULL, "fullName" character varying, "company" character varying, "userRole" "public"."users_userrole_enum" NOT NULL DEFAULT 'contractor', "profilePhoto" text, "isEmailVerified" boolean NOT NULL DEFAULT false, "isPhoneVerified" boolean NOT NULL DEFAULT false, "twoFactorEnabled" boolean NOT NULL DEFAULT false, "refreshToken" text, "lastLogin" TIMESTAMP, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "UQ_1e3d0240b49c40521aaeb953293" UNIQUE ("phoneNumber"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9acf5b718fdc83bc4f6d6b9e86" ON "users" ("userRole") `);
        await queryRunner.query(`CREATE INDEX "IDX_409a0298fdd86a6495e23c25c6" ON "users" ("isActive") `);
        await queryRunner.query(`CREATE TABLE "suppliers" ("userId" uuid NOT NULL, "name" character varying NOT NULL, "ownerName" character varying, "website" character varying, "shopAddress" text, "address" json, "materialCategories" text NOT NULL DEFAULT '', "specialization" text NOT NULL DEFAULT '', "verificationStatus" character varying NOT NULL DEFAULT 'pending', "rating" numeric(2,1) NOT NULL DEFAULT '0', "leadTime" character varying NOT NULL DEFAULT '7-14 days', "minimumOrderValue" numeric(10,2) NOT NULL DEFAULT '0', "currency" character varying NOT NULL DEFAULT 'USD', "isActive" boolean NOT NULL DEFAULT true, "description" text, "rcNumber" character varying, "tin" character varying, "bankName" character varying, "accountNumber" character varying, "accountName" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8b6a94866e7d6ac179bbb67a1f8" PRIMARY KEY ("userId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5b5720d9645cee7396595a16c9" ON "suppliers" ("name") `);
        await queryRunner.query(`CREATE INDEX "IDX_b21907318520e9f8719124d6ab" ON "suppliers" ("rating") `);
        await queryRunner.query(`CREATE INDEX "IDX_876c06b5396f3c4acb7144ca92" ON "suppliers" ("isActive") `);
        await queryRunner.query(`CREATE TYPE "public"."materials_sourcemethod_enum" AS ENUM('upload', 'paste', 'manual')`);
        await queryRunner.query(`CREATE TABLE "materials" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "quoteId" uuid NOT NULL, "name" character varying NOT NULL, "description" text, "quantity" numeric(10,2) NOT NULL, "unit" character varying NOT NULL DEFAULT 'pcs', "specification" text, "category" character varying, "brand" character varying, "estimatedUnitPrice" numeric(10,2), "estimatedTotalPrice" numeric(10,2), "currency" character varying NOT NULL DEFAULT 'USD', "sourceMethod" "public"."materials_sourcemethod_enum" NOT NULL DEFAULT 'manual', "notes" text, "isReviewed" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_2fd1a93ecb222a28bef28663fa0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e94e1d8b3423ddb2ec742fba7e" ON "materials" ("isReviewed") `);
        await queryRunner.query(`CREATE INDEX "IDX_5a153c7ad1e21418c7af9ac89f" ON "materials" ("category") `);
        await queryRunner.query(`CREATE INDEX "IDX_5825aaa342375e5055ef5dc873" ON "materials" ("quoteId") `);
        await queryRunner.query(`CREATE TYPE "public"."contractor_projects_status_enum" AS ENUM('draft', 'review_quotes', 'in_progress', 'completed', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "contractor_projects" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "projectName" character varying NOT NULL, "description" text, "deliveryLocation" character varying NOT NULL, "expectedDeliveryDate" TIMESTAMP, "notes" text, "status" "public"."contractor_projects_status_enum" NOT NULL DEFAULT 'draft', "totalBudget" numeric(12,2) NOT NULL DEFAULT '0', "totalSpent" numeric(12,2) NOT NULL DEFAULT '0', "quotesCount" integer NOT NULL DEFAULT '0', "materialsCount" integer NOT NULL DEFAULT '0', "currency" character varying NOT NULL DEFAULT 'NGN', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b6f5b24ddddf82803f6f922cd15" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_33c47c498760e3bf4e9807a134" ON "contractor_projects" ("userId", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_ebed6461278769b5c2aece91b0" ON "contractor_projects" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_ff5d0e5dd398e65b91888279bf" ON "contractor_projects" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_1ff61566023a226472e307e829" ON "contractor_projects" ("userId") `);
        await queryRunner.query(`CREATE TYPE "public"."quotes_status_enum" AS ENUM('draft', 'in-review', 'finalized', 'archived')`);
        await queryRunner.query(`CREATE TABLE "quotes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "projectId" uuid, "title" character varying, "description" text, "status" "public"."quotes_status_enum" NOT NULL DEFAULT 'draft', "totalEstimatedCost" numeric(12,2) NOT NULL DEFAULT '0', "currency" character varying NOT NULL DEFAULT 'USD', "materialsCount" integer NOT NULL DEFAULT '0', "suppliersCount" integer NOT NULL DEFAULT '0', "notes" text, "deadline" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_99a0e8bcbcd8719d3a41f23c263" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_dbebc7fcdeb052318c99d2c23a" ON "quotes" ("projectId") `);
        await queryRunner.query(`CREATE INDEX "IDX_b9b65a092b763d6c54175153eb" ON "quotes" ("userId", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_f43c6dc5025ec8a9a3a2414686" ON "quotes" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_e1fc1db17214b25db2adc52ffd" ON "quotes" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_8bad8bd49d1dd6954b46366349" ON "quotes" ("userId") `);
        await queryRunner.query(`CREATE TYPE "public"."supplier_quotes_status_enum" AS ENUM('pending', 'quoted', 'accepted', 'rejected')`);
        await queryRunner.query(`CREATE TABLE "supplier_quotes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "quoteId" uuid NOT NULL, "supplierId" uuid NOT NULL, "materials" json NOT NULL DEFAULT '[]', "totalCost" numeric(12,2) NOT NULL DEFAULT '0', "currency" character varying NOT NULL DEFAULT 'USD', "estimatedDelivery" TIMESTAMP, "status" "public"."supplier_quotes_status_enum" NOT NULL DEFAULT 'pending', "notes" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_075c9610bd79ae6085358248013" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5335ffa9c3fa811e90e8eee25b" ON "supplier_quotes" ("quoteId", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_d97cc7de9b37e17426e4ce3736" ON "supplier_quotes" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_af0267211b254d8afd850ab3ef" ON "supplier_quotes" ("supplierId") `);
        await queryRunner.query(`CREATE INDEX "IDX_c3d1136467bf699820f2fff9eb" ON "supplier_quotes" ("quoteId") `);
        await queryRunner.query(`CREATE TABLE "user_settings" ("userId" uuid NOT NULL, "pushNotifications" boolean NOT NULL DEFAULT true, "emailAlerts" boolean NOT NULL DEFAULT true, "smsAlerts" boolean NOT NULL DEFAULT true, "orderUpdates" boolean NOT NULL DEFAULT true, "quoteNotifications" boolean NOT NULL DEFAULT true, "marketingEmails" boolean NOT NULL DEFAULT true, "language" character varying NOT NULL DEFAULT 'en', "preferredCurrency" character varying NOT NULL DEFAULT 'NGN', "timezone" character varying, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_986a2b6d3c05eb4091bb8066f78" PRIMARY KEY ("userId"))`);
        await queryRunner.query(`CREATE TYPE "public"."payments_paymenttype_enum" AS ENUM('payment', 'refund', 'escrow')`);
        await queryRunner.query(`CREATE TYPE "public"."payments_direction_enum" AS ENUM('sent', 'received')`);
        await queryRunner.query(`CREATE TYPE "public"."payments_status_enum" AS ENUM('pending', 'processing', 'completed', 'failed', 'refunded')`);
        await queryRunner.query(`CREATE TABLE "payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "orderId" uuid, "recipientName" character varying NOT NULL, "amount" numeric(12,2) NOT NULL, "currency" character varying NOT NULL DEFAULT 'NGN', "paymentType" "public"."payments_paymenttype_enum" NOT NULL DEFAULT 'payment', "direction" "public"."payments_direction_enum" NOT NULL, "status" "public"."payments_status_enum" NOT NULL DEFAULT 'completed', "transactionReference" character varying NOT NULL, "paymentMethod" character varying, "description" text, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_197ab7af18c93fbb0c9b28b4a59" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8277a466232344577740a61344" ON "payments" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_4ac4750572840fe333fff064cf" ON "payments" ("direction") `);
        await queryRunner.query(`CREATE INDEX "IDX_b22829e26749c1c1b773506e5f" ON "payments" ("paymentType") `);
        await queryRunner.query(`CREATE INDEX "IDX_d35cb3c13a18e1ea1705b2817b" ON "payments" ("userId") `);
        await queryRunner.query(`CREATE TYPE "public"."order_items_status_enum" AS ENUM('pending', 'confirmed', 'packed', 'shipped', 'delivered', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "order_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "orderId" uuid NOT NULL, "supplierId" uuid NOT NULL, "materialId" uuid, "itemName" character varying NOT NULL, "category" character varying, "quantity" numeric(10,2) NOT NULL, "unit" character varying NOT NULL, "pricePerUnit" numeric(12,2) NOT NULL, "totalPrice" numeric(12,2) NOT NULL, "deliveryTime" character varying, "availability" character varying, "status" "public"."order_items_status_enum" NOT NULL DEFAULT 'pending', CONSTRAINT "PK_005269d8574e6fac0493715c308" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ee36de075d90150ce8ce727bfc" ON "order_items" ("supplierId") `);
        await queryRunner.query(`CREATE INDEX "IDX_f1d359a55923bb45b057fbdab0" ON "order_items" ("orderId") `);
        await queryRunner.query(`CREATE TYPE "public"."orders_status_enum" AS ENUM('pending', 'paid', 'processing', 'shipped', 'delivered', 'cancelled', 'disputed', 'completed')`);
        await queryRunner.query(`CREATE TYPE "public"."orders_escrowstatus_enum" AS ENUM('none', 'funds_held', 'released_to_client', 'disputed')`);
        await queryRunner.query(`CREATE TYPE "public"."orders_paymentstatus_enum" AS ENUM('pending', 'processing', 'completed', 'failed', 'refunded')`);
        await queryRunner.query(`CREATE TABLE "orders" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "orderNumber" character varying NOT NULL, "userId" uuid NOT NULL, "quoteId" uuid, "subtotal" numeric(12,2) NOT NULL DEFAULT '0', "deliveryFee" numeric(12,2) NOT NULL DEFAULT '0', "serviceFee" numeric(12,2) NOT NULL DEFAULT '0', "totalAmount" numeric(12,2) NOT NULL DEFAULT '0', "currency" character varying NOT NULL DEFAULT 'NGN', "status" "public"."orders_status_enum" NOT NULL DEFAULT 'pending', "escrowStatus" "public"."orders_escrowstatus_enum" NOT NULL DEFAULT 'none', "paymentStatus" "public"."orders_paymentstatus_enum" NOT NULL DEFAULT 'pending', "paymentMethod" character varying, "transactionReference" character varying, "contactName" character varying NOT NULL, "contactPhone" character varying NOT NULL, "deliveryAddress" text NOT NULL, "deliveryNotes" text, "paidAt" TIMESTAMP, "shippedAt" TIMESTAMP, "deliveredAt" TIMESTAMP, "disputedAt" TIMESTAMP, "completedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_59b0c3b34ea0fa5562342f24143" UNIQUE ("orderNumber"), CONSTRAINT "PK_710e2d4957aa5878dfe94e4ac2f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1f4b9818a08b822a31493fdee9" ON "orders" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_775c9f06fc27ae3ff8fb26f2c4" ON "orders" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_151b79a83ba240b0cb31b2302d" ON "orders" ("userId") `);
        await queryRunner.query(`CREATE TYPE "public"."kyc_documents_documenttype_enum" AS ENUM('nin_slip', 'drivers_license', 'voters_card', 'cac_certificate')`);
        await queryRunner.query(`CREATE TYPE "public"."kyc_documents_verificationstatus_enum" AS ENUM('pending', 'under_review', 'verified', 'rejected')`);
        await queryRunner.query(`CREATE TABLE "kyc_documents" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "documentType" "public"."kyc_documents_documenttype_enum" NOT NULL, "documentUrl" character varying(500) NOT NULL, "documentNumber" character varying(255), "verificationStatus" "public"."kyc_documents_verificationstatus_enum" NOT NULL DEFAULT 'pending', "rejectionReason" text, "verifiedBy" uuid, "verifiedAt" TIMESTAMP, "fileSize" character varying(100), "mimeType" character varying(50), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_02e49877f1578e6285f84e57ab6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7be21d95704317eb5029d299fb" ON "kyc_documents" ("verificationStatus") `);
        await queryRunner.query(`CREATE INDEX "IDX_0a3afb0117f604ede21112e939" ON "kyc_documents" ("userId", "documentType") `);
        await queryRunner.query(`CREATE TYPE "public"."contractors_status_enum" AS ENUM('active', 'pending', 'suspended')`);
        await queryRunner.query(`CREATE TABLE "contractors" ("userId" uuid NOT NULL, "fullName" character varying(255) NOT NULL, "company" character varying(255), "profilePhoto" character varying(500), "businessAddress" text, "preferences" jsonb, "status" "public"."contractors_status_enum" NOT NULL DEFAULT 'active', "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_20f0a65703cf761f6d93dd8ca14" PRIMARY KEY ("userId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_contractor_user_id" ON "contractors" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_contractor_is_active" ON "contractors" ("isActive") `);
        await queryRunner.query(`CREATE TABLE "user_otps" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "phoneNumber" character varying NOT NULL, "otp" character varying, "pinId" character varying, "expiresAt" TIMESTAMP NOT NULL, "verified" boolean NOT NULL DEFAULT false, "attempts" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_058cf61bf2024c3a3c3bfc4e1b7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_92c28f29d6dc106d13a8bd568c" ON "user_otps" ("phoneNumber", "expiresAt") `);
        await queryRunner.query(`CREATE TABLE "platform_settings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "platformName" character varying NOT NULL DEFAULT 'MatGrid', "supportEmail" character varying, "supportPhone" character varying, "platformFeePercent" numeric(5,2) NOT NULL DEFAULT '2.5', "escrowHoldPeriodDays" integer NOT NULL DEFAULT '7', "maintenanceMode" boolean NOT NULL DEFAULT false, "smsNotifications" boolean NOT NULL DEFAULT true, "autoApproveVerifiedSuppliers" boolean NOT NULL DEFAULT false, "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_2934aeb70ec285196dcab4a2e96" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."escrow_transactions_escrowstatus_enum" AS ENUM('held', 'released', 'disputed')`);
        await queryRunner.query(`CREATE TYPE "public"."escrow_transactions_deliverystatus_enum" AS ENUM('in_transit', 'delivered', 'delivery_confirmed', 'awaiting_confirmation')`);
        await queryRunner.query(`CREATE TABLE "escrow_transactions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "escrowId" character varying NOT NULL, "orderId" uuid NOT NULL, "orderNumber" character varying NOT NULL, "contractorId" uuid NOT NULL, "contractorName" character varying NOT NULL, "supplierId" uuid NOT NULL, "supplierName" character varying NOT NULL, "amount" numeric(12,2) NOT NULL, "currency" character varying NOT NULL DEFAULT 'NGN', "escrowStatus" "public"."escrow_transactions_escrowstatus_enum" NOT NULL DEFAULT 'held', "deliveryStatus" "public"."escrow_transactions_deliverystatus_enum" NOT NULL DEFAULT 'in_transit', "releasedAt" TIMESTAMP, "releaseNotes" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_8d6f7bcb38124b2da80c1b4dca8" UNIQUE ("escrowId"), CONSTRAINT "PK_529d3ac2fa1b343b7beb59bd945" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_beef8adfec373932d031f8aebf" ON "escrow_transactions" ("supplierId") `);
        await queryRunner.query(`CREATE INDEX "IDX_b95c7c4040fcb624dbb110075e" ON "escrow_transactions" ("contractorId") `);
        await queryRunner.query(`CREATE INDEX "IDX_ce066bb4e31e80d2e6023354ac" ON "escrow_transactions" ("escrowStatus") `);
        await queryRunner.query(`CREATE INDEX "IDX_aa97c14e95954a89051baa0fad" ON "escrow_transactions" ("orderId") `);
        await queryRunner.query(`ALTER TABLE "suppliers" ADD CONSTRAINT "FK_8b6a94866e7d6ac179bbb67a1f8" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "materials" ADD CONSTRAINT "FK_5825aaa342375e5055ef5dc8738" FOREIGN KEY ("quoteId") REFERENCES "quotes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "contractor_projects" ADD CONSTRAINT "FK_1ff61566023a226472e307e8290" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quotes" ADD CONSTRAINT "FK_8bad8bd49d1dd6954b46366349c" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quotes" ADD CONSTRAINT "FK_dbebc7fcdeb052318c99d2c23a6" FOREIGN KEY ("projectId") REFERENCES "contractor_projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "supplier_quotes" ADD CONSTRAINT "FK_c3d1136467bf699820f2fff9ebf" FOREIGN KEY ("quoteId") REFERENCES "quotes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "supplier_quotes" ADD CONSTRAINT "FK_af0267211b254d8afd850ab3ef1" FOREIGN KEY ("supplierId") REFERENCES "suppliers"("userId") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_settings" ADD CONSTRAINT "FK_986a2b6d3c05eb4091bb8066f78" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_d35cb3c13a18e1ea1705b2817b1" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_f1d359a55923bb45b057fbdab0d" FOREIGN KEY ("orderId") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_ee36de075d90150ce8ce727bfc2" FOREIGN KEY ("supplierId") REFERENCES "suppliers"("userId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_aac51684cd5ca4490d77a2bd769" FOREIGN KEY ("materialId") REFERENCES "materials"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_151b79a83ba240b0cb31b2302d1" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "kyc_documents" ADD CONSTRAINT "FK_5582c3140c9cdbc6e5f61e05773" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "contractors" ADD CONSTRAINT "FK_20f0a65703cf761f6d93dd8ca14" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "contractors" DROP CONSTRAINT "FK_20f0a65703cf761f6d93dd8ca14"`);
        await queryRunner.query(`ALTER TABLE "kyc_documents" DROP CONSTRAINT "FK_5582c3140c9cdbc6e5f61e05773"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_151b79a83ba240b0cb31b2302d1"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_aac51684cd5ca4490d77a2bd769"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_ee36de075d90150ce8ce727bfc2"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_f1d359a55923bb45b057fbdab0d"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_d35cb3c13a18e1ea1705b2817b1"`);
        await queryRunner.query(`ALTER TABLE "user_settings" DROP CONSTRAINT "FK_986a2b6d3c05eb4091bb8066f78"`);
        await queryRunner.query(`ALTER TABLE "supplier_quotes" DROP CONSTRAINT "FK_af0267211b254d8afd850ab3ef1"`);
        await queryRunner.query(`ALTER TABLE "supplier_quotes" DROP CONSTRAINT "FK_c3d1136467bf699820f2fff9ebf"`);
        await queryRunner.query(`ALTER TABLE "quotes" DROP CONSTRAINT "FK_dbebc7fcdeb052318c99d2c23a6"`);
        await queryRunner.query(`ALTER TABLE "quotes" DROP CONSTRAINT "FK_8bad8bd49d1dd6954b46366349c"`);
        await queryRunner.query(`ALTER TABLE "contractor_projects" DROP CONSTRAINT "FK_1ff61566023a226472e307e8290"`);
        await queryRunner.query(`ALTER TABLE "materials" DROP CONSTRAINT "FK_5825aaa342375e5055ef5dc8738"`);
        await queryRunner.query(`ALTER TABLE "suppliers" DROP CONSTRAINT "FK_8b6a94866e7d6ac179bbb67a1f8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_aa97c14e95954a89051baa0fad"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ce066bb4e31e80d2e6023354ac"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b95c7c4040fcb624dbb110075e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_beef8adfec373932d031f8aebf"`);
        await queryRunner.query(`DROP TABLE "escrow_transactions"`);
        await queryRunner.query(`DROP TYPE "public"."escrow_transactions_deliverystatus_enum"`);
        await queryRunner.query(`DROP TYPE "public"."escrow_transactions_escrowstatus_enum"`);
        await queryRunner.query(`DROP TABLE "platform_settings"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_92c28f29d6dc106d13a8bd568c"`);
        await queryRunner.query(`DROP TABLE "user_otps"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_contractor_is_active"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_contractor_user_id"`);
        await queryRunner.query(`DROP TABLE "contractors"`);
        await queryRunner.query(`DROP TYPE "public"."contractors_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0a3afb0117f604ede21112e939"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7be21d95704317eb5029d299fb"`);
        await queryRunner.query(`DROP TABLE "kyc_documents"`);
        await queryRunner.query(`DROP TYPE "public"."kyc_documents_verificationstatus_enum"`);
        await queryRunner.query(`DROP TYPE "public"."kyc_documents_documenttype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_151b79a83ba240b0cb31b2302d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_775c9f06fc27ae3ff8fb26f2c4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1f4b9818a08b822a31493fdee9"`);
        await queryRunner.query(`DROP TABLE "orders"`);
        await queryRunner.query(`DROP TYPE "public"."orders_paymentstatus_enum"`);
        await queryRunner.query(`DROP TYPE "public"."orders_escrowstatus_enum"`);
        await queryRunner.query(`DROP TYPE "public"."orders_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f1d359a55923bb45b057fbdab0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ee36de075d90150ce8ce727bfc"`);
        await queryRunner.query(`DROP TABLE "order_items"`);
        await queryRunner.query(`DROP TYPE "public"."order_items_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d35cb3c13a18e1ea1705b2817b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b22829e26749c1c1b773506e5f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4ac4750572840fe333fff064cf"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8277a466232344577740a61344"`);
        await queryRunner.query(`DROP TABLE "payments"`);
        await queryRunner.query(`DROP TYPE "public"."payments_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."payments_direction_enum"`);
        await queryRunner.query(`DROP TYPE "public"."payments_paymenttype_enum"`);
        await queryRunner.query(`DROP TABLE "user_settings"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c3d1136467bf699820f2fff9eb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_af0267211b254d8afd850ab3ef"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d97cc7de9b37e17426e4ce3736"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5335ffa9c3fa811e90e8eee25b"`);
        await queryRunner.query(`DROP TABLE "supplier_quotes"`);
        await queryRunner.query(`DROP TYPE "public"."supplier_quotes_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8bad8bd49d1dd6954b46366349"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e1fc1db17214b25db2adc52ffd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f43c6dc5025ec8a9a3a2414686"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b9b65a092b763d6c54175153eb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dbebc7fcdeb052318c99d2c23a"`);
        await queryRunner.query(`DROP TABLE "quotes"`);
        await queryRunner.query(`DROP TYPE "public"."quotes_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1ff61566023a226472e307e829"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ff5d0e5dd398e65b91888279bf"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ebed6461278769b5c2aece91b0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_33c47c498760e3bf4e9807a134"`);
        await queryRunner.query(`DROP TABLE "contractor_projects"`);
        await queryRunner.query(`DROP TYPE "public"."contractor_projects_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5825aaa342375e5055ef5dc873"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5a153c7ad1e21418c7af9ac89f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e94e1d8b3423ddb2ec742fba7e"`);
        await queryRunner.query(`DROP TABLE "materials"`);
        await queryRunner.query(`DROP TYPE "public"."materials_sourcemethod_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_876c06b5396f3c4acb7144ca92"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b21907318520e9f8719124d6ab"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5b5720d9645cee7396595a16c9"`);
        await queryRunner.query(`DROP TABLE "suppliers"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_409a0298fdd86a6495e23c25c6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9acf5b718fdc83bc4f6d6b9e86"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_userrole_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97f324118f8227531259b3a558"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_821beb737b3c154e7cbc83aff4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3816a9b513ab119616229d3356"`);
        await queryRunner.query(`DROP TABLE "faqs"`);
    }

}
